name: dash-gallery-indicators
channels:
- conda-forge
dependencies:
- dash
- jupyter_dash
- dash_bootstrap components
- dash.dependencies
- plotly.express
- plotly.graph_objects
- plotly.io
- folium
- numpy
- pandas
- jupyterlab>=3.1
- voila>=0.2.11